-- =========================================================================
-- SCRIPT DE RESTAURACIÓN DE LAS TABLAS DEL CARRITO Y PEDIDOS UNIFICADOS
-- Ejecuta este script en el Editor SQL de Supabase para reparar el carrito.
-- =========================================================================

-- 1. CREACIÓN DE TABLAS DE CARRITO
CREATE TABLE IF NOT EXISTS public.carrito (
    id bigint generated by default as identity primary key,
    id_cliente bigint not null,
    activo boolean default true,
    creado_en timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.carrito_detalle (
    id bigint generated by default as identity primary key,
    id_carrito bigint references public.carrito(id) on delete cascade on update cascade,
    id_variante bigint references public.producto_variantes(id_variante) on delete cascade on update cascade,
    cantidad integer not null default 1,
    precio_unitario numeric(10,2) not null,
    fecha date,
    hora text,
    domicilio boolean,
    sabor text,
    dedicatoria text,
    observaciones text,
    agregado_en timestamp with time zone default timezone('utc'::text, now())
);

-- 2. CREACIÓN DE TABLAS DEL NUEVO SISTEMA DE PEDIDOS
CREATE TABLE IF NOT EXISTS public.pedidos (
    id_pedido bigint generated by default as identity primary key,
    folio text unique not null,
    id_cliente bigint not null,
    fecha_entrega date,
    hora_entrega text,
    tipo_entrega text default 'sucursal',
    costo_flete numeric(10,2) default 0.00,
    total numeric(10,2) not null,
    anticipo numeric(10,2) not null,
    saldo numeric(10,2) not null,
    estado text default 'pendiente',
    creado_en timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido (
    id_detalle bigint generated by default as identity primary key,
    id_pedido bigint references public.pedidos(id_pedido) on delete cascade on update cascade,
    id_variante bigint references public.producto_variantes(id_variante) on delete cascade on update cascade,
    cantidad integer not null,
    precio_unitario numeric(10,2) not null,
    sabor text,
    dedicatoria text,
    observaciones text
);

CREATE TABLE IF NOT EXISTS public.pagos (
    id_pago bigint generated by default as identity primary key,
    id_pedido bigint references public.pedidos(id_pedido) on delete cascade on update cascade,
    metodo_pago text not null,
    monto numeric(10,2) not null,
    estado_pago text default 'pendiente',
    comprobante_url text,
    creado_en timestamp with time zone default timezone('utc'::text, now())
);

-- 3. POLÍTICAS DE SEGURIDAD (RLS - IMPORTANTE PARA QUE FUNCIONE LA PÁGINA)
ALTER TABLE public.carrito ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrito_detalle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;

-- Crear políticas permisivas para clientes anónimos/registrados (MVP Front-end)
DO $$
BEGIN
    -- Permitir TODO en Carrito
    EXECUTE 'CREATE POLICY "Permitir full access carrito" ON public.carrito FOR ALL USING (true) WITH CHECK (true)';
    EXECUTE 'CREATE POLICY "Permitir full access carrito detalle" ON public.carrito_detalle FOR ALL USING (true) WITH CHECK (true)';
    
    -- Permitir TODO en Pedidos Unificados
    EXECUTE 'CREATE POLICY "Permitir full access pedidos" ON public.pedidos FOR ALL USING (true) WITH CHECK (true)';
    EXECUTE 'CREATE POLICY "Permitir full access detalle pedidos" ON public.detalle_pedido FOR ALL USING (true) WITH CHECK (true)';
    EXECUTE 'CREATE POLICY "Permitir full access pagos" ON public.pagos FOR ALL USING (true) WITH CHECK (true)';
EXCEPTION WHEN OTHERS THEN
    -- Si ya existen las políticas, las ignoramos.
END $$;
